name: hnog_pokerwall
description: HNOG POKERWALL
repository: https://github.com/flutter/gallery
version: 0.0.1+000001

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore

environment:
  flutter: ^2.2.0
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  get:
  countdown_progress_indicator: ^0.1.2
  duration_picker: ^1.1.0+1
  form_field_validator: ^1.1.0
  google_fonts: ^3.0.1
  flutter_html: ^0.11.1
  checkbox_formfield: ^0.2.0
  flutter_svg: ^1.1.0
  counter: ^0.2.2
  datetime_picker_formfield: ^2.0.0
  multiselect_formfield: ^0.1.7
  process_run: ^0.12.3+2
  web_socket_channel: ^2.2.0
  marquee_text: ^2.5.0+1
  sweetalertv2: ^0.0.2 

dev_dependencies:
  flutter_launcher_icons:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.2
  grinder: ^0.9.0
  path: ^1.8.0
  pedantic: ^1.11.0
  string_scanner: ^1.1.0
  test: ^1.16.8
  web_benchmarks: ^0.0.5

flutter:
  # deferred-components:
  #   - name: crane
  #     libraries:
  #       # Only one library from the loading unit is necessary.
  #       - package:gallery/studies/crane/app.dart
  #     assets:
  #       - lib/assets
  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/1x/
    - assets/images/cards/
    - assets/images/Cantos/
  generate: true
  uses-material-design: true
  # fonts:
  #   - family: GalleryIcons
  #     fonts:
  #       - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
flutter_localizations:
  sdk: flutter
  intl: 0.16.1

flutter_intl:
  enabled: true

flutter_icons:
  android: "icon"
  ios: false
  image_path_ios: "assets/images/1x/icon.png"
  image_path_android: "assets/images/1x/icon.png"
  adaptive_icon_background: "assets/images/1x/icon.png"
  adaptive_icon_foreground: "assets/images/1x/icon.png"
